version: 2.1

commands:
  set_up_unit_test_environment:
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Run SETUP
          command: ./setup.sh -gtest
      - run:
          name: Install LCOV
          command: apt update && sudo apt install -y lcov
  set_up_regression_test_environment:
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Installing PYHTON
          command: 'apt-get update && sudo apt install -y python3'
      - run:
          name: Run SETUP
          command: ./setup.sh
  set_up_pybind11_test_environment:
    steps:
      - checkout
      - run:
          name: Installing SUDO
          command: 'apt-get update && apt install -y sudo && rm -rf /var/lib/apt/lists/*'
      - run:
          name: Run SETUP
          command: ./setup.sh -pybind11

  build_tests:
    steps:
      - run:
          name: Build HAMT-TESTS
          command: 'mkdir build-hamt-tests && cd build-hamt-tests && cmake -DCMAKE_BUILD_TYPE=Release ../test/ && make'
  build_hamt:
    steps:
      - run:
          name: Build HAMT
          command: 'mkdir build-hamt && cd build-hamt && cmake -DCMAKE_BUILD_TYPE=Release ../src/ && make'
  build_pyhamt:
    steps:
      - run:
          name: Build PYHAMT
          command: 'cd /pybind11/pyhamt && cmake -DCMAKE_BUILD_TYPE=Release ../pybind11/ && make'

  run_unit_tests:
    steps:
      - run:
          name: Run unit tests
          command: mkdir test-results && mkdir test-results/gtest && ./build-hamt-tests/unit_tests/unit_tests --gtest_output="xml:./test-results/gtest/results.xml"
      - store_test_results:
          path: test-results
      - run:
          name: Run LCOV
          command: |
            lcov --capture --directory ./build-hamt-tests/unit_tests/ --output-file ./build-hamt-tests/unit_tests/coverage.info
            lcov -r "./build-hamt-tests/unit_tests/coverage.info" "*.moc" "*moc_*.cpp" "*/test/*" "*/unit_tests/*" "*/gtest/*" "*/c++/*" "*/Core/*" "*/Eigen/*" "*/gcc/*" -o "./build-hamt-tests/unit_tests/coverage-filtered.info"
            genhtml ./build-hamt-tests/unit_tests/coverage-filtered.info --output-directory coverage
      - store_artifacts:
          path: coverage
  run_analytical_tests_cartesian:
    steps:
      - run:
          name: Run cartesian homogenous block execution test
          command: ./build-hamt/hamt ./test/regression/homogeneous_cartesian/input.in
      - run:
          name: Run cartesian homogenous block analysis vertical
          command: cd ./test/regression/homogeneous_cartesian/ && python3 asses.py ../../../reg_car_hom.csv reg_car_hom_ref.csv
      - run:
          name: Run cartesian homogenous block analysis horizontal
          command: cd ./test/regression/homogeneous_cartesian/ && python3 asses.py ../../../reg_car_hom_1.csv reg_car_hom_1_ref.csv
      - run:
          name: Run cartesian homogenous block analysis horizontal heterogen.
          command: cd ./test/regression/homogeneous_cartesian/ && python3 asses.py ../../../reg_car_hom_2.csv reg_car_hom_2_ref.csv
      - run:
          name: Run cartesian homogenous block analysis vertical heterogen.
          command: cd ./test/regression/homogeneous_cartesian/ && python3 asses.py ../../../reg_car_hom_3.csv reg_car_hom_3_ref.csv
  run_analytical_tests_cylinder:
    steps:
      - run:
          name: Run cartesian homogenous cylinder block execution test
          command: ./build-hamt/hamt ./test/regression/homogeneous_cylinder/input.in
      - run:
          name: Run cartesian homogenous cylinder block analysis vertical
          command: cd ./test/regression/homogeneous_cylinder/ && python3 asses.py ../../../cylinder_test.csv cylinder_test.csv

executors:
  docker-bionic:
    docker:
      - image: "ubuntu:bionic"

jobs:
  unit_tests:
    executor: docker-bionic
    steps:
      - set_up_unit_test_environment
      - build_tests
      - run_unit_tests
  analytical_tests:
    executor: docker-bionic
    steps:
      - set_up_regression_test_environment
      - build_hamt
      - run_analytical_tests_cartesian
      - run_analytical_tests_cylinder
  pybind11_tests:
    executor: docker-bionic
    steps:
      - set_up_pybind11_test_environment
      - build_pyhamt

workflows:
  build-and-run-tests:
    jobs:
      - unit_tests
      - analytical_tests
      - pybind11_tests
